import '@/styles/globals.css';
import React from 'react';
import { ReactNode } from 'react';
//import '@/styles/Home.module.css';
import { Montserrat } from 'next/font/google';
import Head from 'next/head';

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-mont',
});

export const metadata = {
  title: 'Portfolio v2.0',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <>
    <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <html lang="en">
      <body
        style={{
          fontFamily: montserrat.style.fontFamily,
        }}
      >
        {children}
      </body>
    </html>
    </>
  );
}