"use client";

import '@/styles/globals.css';
import React from 'react';
import { ReactNode } from 'react';
import { Montserrat } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Script from 'next/script';
import { motion, AnimatePresence } from 'framer-motion';
import { useRouter } from 'next/navigation';
import TransitionEffect from '@/components/TransitionEffect';

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-mont',
});

// export const metadata = {
//   title: 'Portfolio v2.0',
//   description: 'Generated by Next.js',
//   icons: {
//     icon: '/favicon.ico',
//   },
// };

export const viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({ children }: { children: ReactNode }) {
  const router = useRouter();
  return (
    <html lang="en">
      <body
        style={{
          fontFamily: montserrat.style.fontFamily,
        }}
        className="bg-light dark:bg-dark w-full min-h-screen"
      >
        <Script id="theme-switcher" strategy="beforeInteractive">
          {`
          if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
          document.documentElement.classList.add('dark')
          } else {
            document.documentElement.classList.remove('dark')
          }
        `}
        </Script>
        <Navbar />
        <AnimatePresence mode='wait' onExitComplete={() => window.scrollTo(0, 0)}>
          <TransitionEffect key={router.asPath} />
          <motion.div key={router.asPath} initial="initial" animate="animate" exit="exit">
          {children}
          </motion.div>
        </AnimatePresence>
        <Footer />
      </body>
    </html>
  );
}
